export default {
  UPDATE_SEARCH_QUERY: 'UPDATE_SEARCH_QUERY',
  UPDATE_PAGINATION: 'UPDATE_PAGINATION',
  SHOW_REPOSITORY_DETAILS: 'SHOW_REPOSITORY_DETAILS',
  HIDE_REPOSITORY_DETAILS: 'HIDE_REPOSITORY_DETAILS',
};
